### PR TITLE
add docker file

### PR DESCRIPTION
**Pull request by billbsing**
initial docker file

### CODE REVIEW

**Comment by mikera** [comment]
Can this go in the convex-cli module?

**Comment by billbsing** [comment]
I depends what you want to use the docker for, if only for CLI then yes, but I would also need to move convex.bat & convex script down to the cli module.
If you want to docker support running the gui then a single docker file at the top or two docker build files one for CLI & the other for GUI.

**Comment by mikera** [comment]
Does anyone run GUIs using docker? I think this is probably CLI specific (same goes for the convex.bat and shell script I guess?)

**Comment by billbsing** [comment]
probably  not, so I'll move all the files over to the convex-cli  sub project

**Comment by billbsing** [comment]
It's all  a bit academic, since the Dockerfile has to be in the parent folder to build the complete library and cli.
When I put it the Dockerfile in convex-cli, I cannot upload the other folders for the docker build, and so cannot build the CLI.

Is it time to break apart the sub projects into separate repos?

**Comment by mikera** [comment]
OK, put it in the parent folder then.

Breaking into separate repos is a bad idea, trust me :-)

**Pull request merged**
