### PR TITLE
Cli log output

### PR DESCRIPTION
**Pull request by billbsing**
adds logging output for the CLI.
The CLI still uses slf4j as the logging mechanism.

I found that changing the log level dynamically during runtime in java is not supported for most loggers.

So the CLI uses logback since the library supports dynamic log level changes..

I had to add the following libraries in the pom.xml:

+ logback-core
+ logback-clasic

### CODE REVIEW

**Comment by mikera** [comment]
Not too keen on having an explicit logging binding in the main dependencies. I think this causes problems later when people try to use Convex as a dependency in their own systems. Can you think of another solution?

Also why do we need dynamic log level changes?

**Comment by billbsing** [comment]
When running the command line , it's easier to debug by setting a parameter (-vv) and looking at the log. If we do not have this then to change log levels the user has to re build with the desired log level flag set.

One possible solution is to split up CLI into a separate package.

**Comment by mikera** [comment]
Perhaps SLF4J lets us switch logging at runtime? Haven't looked into it much but it seems to have some ServiceLoader features

**Comment by billbsing** [comment]
Looking at the blogs and manual, SLF4J is only a logging library, but does not pipe any results out to a file/console. We need to load in our own log reporting device, `sl4j-simple` (there are a few more older logging older libs that can do this) or `logback`. 

Because I do not want to re-write log libraries again, `logback` does the job.

This repo is not really a library with a GUI and CLI, I think we should split this project up into three separate pom.xml packages or even better three separate repos. CLI/GUI/Core.

The CLI does not need the dependency of swagger, and GUI does not need piccoli and logback, and the library does not need all CLI & GUI dependencies.

**Comment by mikera** [comment]
Please issue a separate PR against develop if you want further logging changes in convex-cli module, thanks!

**Pull request closed without merging**
