### PR TITLE
Fix botched refactoring in trust library

### PR DESCRIPTION
**Pull request by helins**
Hm, something went obviously wrong when I moved stuff around. That should be better.
Added a few tests assertions this time...

### CODE REVIEW

**Comment by mikera** [comment]
Two comments:

1) The cvx tests don't seem to be included as part of the build. Can they be run without a Clojure test dependency? If not they probably don't belong in convex-core. If yes they should be hooked into the standard unit testing
2) I think I prefer a cast error if a trust monitor is used that isn't an address. Isn't that always a mistake?

**Comment by helins** [comment]
1. They can run fast with the native CVX runner. But overall, yes, the current situation is not ideal. The problem is that writing such tests in Java is even less ideal, not to say a bad idea. Porting some of them to CVX (a while ago) clearly improved their quality and allowed for going much further. In Java, you quickly end up in a situation where you have to do bizarre string manipulations and it's just too hard to reach the same level of accuracy. Fine for testing trivial situations like simple core functions, bad for anything beyond.

Plus, using the CVX runner for dev is clearly a superior experience to anything else, even the sandbox. You get a REPL, can quickly reload, reseting the state or not as you wish, etc. I'd argue it's hard not including it as part of the normal workflow for the sake of being productive. In any case, it's best colocating tests with their main target.

2. Feel free to amend but generally speaking, in such a dynamic lang, it's a more zen approach pushing validation to the edges. In this case, let devs use the predicate if they have doubts about inputs. There are many situations where you'll know that what you have is an address. It's especially relevant in a metered runtime: promoting predatory type checking incurs a real cost and being too paranoid becomes expensive. As opposed to promoting sanitation at the edges and then knowing you're good forever.

**Comment by helins** [comment]
Yes so the native variant is the best solution at the moment (negligible startup time, no compromise on test quality).

**Comment by mikera** [comment]
Closing since superseded by more recent work.

**Pull request closed without merging**
